### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by mariotacke** [pwielgolaski/teamcity-revisions#2]
I wanted to reach out and say thank you for this project. Sometimes it's the little things that annoy you the most. For us, it was not being able to use short git commit hashes in the FileContentReplacer build feature. 

Thanks to you, we are now able to use short git commit hashes!

👏 👍 🥇

**Comment by pwielgolaski** [comment]
Thank you for sharing, it is nice to hear that it helps others.
We had also similar case in my project so it was inspiration.
